##name: Rodar todos os testes
##on:
##  push: branches:[main, master]
##  pull_request: branches:[main,master]
##  jobs:
##    test:
##      timeout-minutes: 60
##      runs-on: ubuntu-latest
##      steps:
##        - uses: actions/checkout@2
##        - uses: actions/setup-node@2
##          with:
##            node-version: '18.x'
##        - name: Install dependencies
##          run: npm ci
##        - name: Install Playwright
##          run: npx playwright install --with-deps
##        - name: Run Jest
##          run: npm run test
##        - name: Run Playwright tests
##          run: npm run test:e2e
